mysql:
  password: ''
  host: 'localhost'
  database: 'test'
  port: 3306
  user: 'root'
  table: 'primecubes_cubes'

hookWithShopGuiPlus: true
cyborgHead: "b42bddb836935110858c6ad211466c76cb1b4473ae4aa85b9a52387232226f9"
guis:
  upgrade:
    title: "PrimeCube {size}"
    items:
      speed:
        item: "85d336e7cc77680d877a54405a3f2be2cb3048deb26e22a626e9b4c0b081960a"
        name: "&2&lSpeed upgrade"
        lore:
          - ""
          - "&bCube regen time: &c{current} &b-> &a{next}"
          - " "
          - "&bCurrent level: &f{currentLevel}"
          - "&bNext level: &f{nextLevel}"
          - "&bPrice to upgrade: &f{priceToUpgrade}"
          - " "
          - "&7Click to level up!"
        loreDoesNotApply:
          - ""
          - "&cThis upgrade does not apply to this cube!"
        position:
          row: 1
          collunm: 2
      layers:
        item: "85d336e7cc77680d877a54405a3f2be2cb3048deb26e22a626e9b4c0b081960a"
        name: "&2&lLayers upgrade"
        lore:
          - ""
          - "&bCube layers: &c{current} &b-> &a{next}"
          - " "
          - "&bCurrent level: &f{currentLevel}"
          - "&bNext level: &f{nextLevel}"
          - "&bPrice to upgrade: &f{priceToUpgrade}"
          - " "
          - "&7Click to level up!"
        loreDoesNotApply:
          - ""
          - "&cThis upgrade does not apply to this cube!"
        position:
          row: 1
          collunm: 3
      storage:
        item: "85d336e7cc77680d877a54405a3f2be2cb3048deb26e22a626e9b4c0b081960a"
        name: "&2&lStorage upgrade"
        lore:
          - ""
          - "&bCube Storage: &c{current} &b-> &a{next}"
          - " "
          - "&bCurrent level: &f{currentLevel}"
          - "&bNext level: &f{nextLevel}"
          - "&bPrice to upgrade: &f{priceToUpgrade}"
          - " "
          - "&7Click to level up!"
        loreDoesNotApply:
          - ""
          - "&cThis upgrade does not apply to this cube!"
        position:
          row: 1
          collunm: 4
      loot:
        item: "85d336e7cc77680d877a54405a3f2be2cb3048deb26e22a626e9b4c0b081960a"
        name: "&2&lLoot upgrade"
        lore:
          - ""
          - "&bCube Loot: &c{current} &b-> &a{next}"
          - " "
          - "&bCurrent level: &f{currentLevel}"
          - "&bNext level: &f{nextLevel}"
          - "&bPrice to upgrade: &f{priceToUpgrade}"
          - " "
          - "&7Click to level up!"
        loreDoesNotApply:
          - ""
          - "&cThis upgrade does not apply to this cube!"
        position:
          row: 1
          collunm: 5
      cyborgSpeed:
        item: "85d336e7cc77680d877a54405a3f2be2cb3048deb26e22a626e9b4c0b081960a"
        name: "&2&lCyborg Speed"
        lore:
          - ""
          - "&bCyborg Speed: &c{current} &b-> &a{next}"
          - " "
          - "&bCurrent level: &f{currentLevel}"
          - "&bNext level: &f{nextLevel}"
          - "&bPrice to upgrade: &f{priceToUpgrade}"
          - " "
          - "&7Click to level up!"
        loreDoesNotApply:
          - ""
          - "&cThis upgrade does not apply to this cube!"
        position:
          row: 1
          collunm: 6
      cyborgFortune:
        item: "85d336e7cc77680d877a54405a3f2be2cb3048deb26e22a626e9b4c0b081960a"
        name: "&2&lCyborg Fortune"
        lore:
          - ""
          - "&bCyborg Fortune maximum multiplier: &c{current} &b-> &a{next}"
          - " "
          - "&bCurrent level: &f{currentLevel}"
          - "&bNext level: &f{nextLevel}"
          - "&bPrice to upgrade: &f{priceToUpgrade}"
          - " "
          - "&7Click to level up!"
        loreDoesNotApply:
          - ""
          - "&cThis upgrade does not apply to this cube!"
        position:
          row: 2
          collunm: 4
      previousGUI:
        item: "arrow"
        name: "&cMain GUI"
        lore:
          - ""
          - "&2<---"
        position:
          row: 3
          collunm: 8
  cube:
    title: "PrimeCube {size}"
    items:
      upgrades:
        item: "85d336e7cc77680d877a54405a3f2be2cb3048deb26e22a626e9b4c0b081960a"
        name: "&2&lUpgrades"
        lore:
          - ""
          - "&aClick to open upgrades!"
        position:
          row: 5
          collunm: 3
      sellAll:
        item: "Diamond"
        name: "&2&lSELL ALL"
        lore:
          - ""
          - "&aPrice: &f{price}"
        position:
          row: 5
          collunm: 5
      remove:
        item: "barrier"
        name: "&4&lRemove"
        lore:
          - ""
          - "&cremove cube"
        position:
          row: 5
          collunm: 8
      nextPage:
        item: "arrow"
        name: "&aNext Page"
        lore:
          - ""
          - "&2--->"
        position:
          row: 2
          collunm: 7
      previousPage:
        item: "arrow"
        name: "&cPrevious Page"
        lore:
          - ""
          - "&2<---"
        position:
          row: 2
          collunm: 1
      glassPane:
        item: "stained_glass_pane:15"
        name: ""
        lore: []

